//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFH.Web.Models.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EFHEntities : DbContext
    {
        public EFHEntities()
            : base("name=EFHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_empresa> tb_empresa { get; set; }
        public DbSet<tb_usuario> tb_usuario { get; set; }
        public DbSet<tb_evento> tb_evento { get; set; }
        public DbSet<tb_agenda_telefonica> tb_agenda_telefonica { get; set; }
        public DbSet<tb_cliente_empresa> tb_cliente_empresa { get; set; }
        public DbSet<tb_detalle_agenda_telefonica> tb_detalle_agenda_telefonica { get; set; }
        public DbSet<tb_detalle_rol> tb_detalle_rol { get; set; }
        public DbSet<tb_fases_proyecto> tb_fases_proyecto { get; set; }
        public DbSet<tb_grupo> tb_grupo { get; set; }
        public DbSet<tb_grupo_usuario> tb_grupo_usuario { get; set; }
        public DbSet<tb_regla> tb_regla { get; set; }
        public DbSet<tb_roles> tb_roles { get; set; }
        public DbSet<tb_tipo_numero> tb_tipo_numero { get; set; }
        public DbSet<tb_tipo_regla> tb_tipo_regla { get; set; }
        public DbSet<tb_estado_proyecto_kanban> tb_estado_proyecto_kanban { get; set; }
        public DbSet<tb_proyecto> tb_proyecto { get; set; }
        public DbSet<tb_criterios_aceptacion> tb_criterios_aceptacion { get; set; }
        public DbSet<tb_plantilla_estados_proyectos_kanban> tb_plantilla_estados_proyectos_kanban { get; set; }
        public DbSet<tb_prioridad> tb_prioridad { get; set; }
        public DbSet<tb_riesgo> tb_riesgo { get; set; }
        public DbSet<tb_tipo_grupo> tb_tipo_grupo { get; set; }
        public DbSet<tb_estado_tarea_kanban> tb_estado_tarea_kanban { get; set; }
        public DbSet<tb_historia_usuario> tb_historia_usuario { get; set; }
        public DbSet<tb_tarea> tb_tarea { get; set; }
    
        public virtual int efh_sp_iniciar_empresa(Nullable<long> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("efh_sp_iniciar_empresa", idEmpresaParameter);
        }
    }
}
