//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFH.Web.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_agenda_telefonica
    {
        public tb_agenda_telefonica()
        {
            this.tb_detalle_agenda_telefonica = new HashSet<tb_detalle_agenda_telefonica>();
        }
    
        public long id_agenda_telefonica { get; set; }
        public string numero_agenda { get; set; }
        public int id_tipo_numero { get; set; }
    
        public virtual ICollection<tb_detalle_agenda_telefonica> tb_detalle_agenda_telefonica { get; set; }
        public virtual tb_tipo_numero tb_tipo_numero { get; set; }
    }
}
