//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFH.Web.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente_empresa
    {
        public long id_cliente { get; set; }
        public long id_empresa { get; set; }
        public string nombre_cliente { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public string nemo { get; set; }
    }
}
