//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFH.Web.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_detalle_agenda_telefonica
    {
        public long id_detalle_agenda { get; set; }
        public Nullable<long> id_empresa { get; set; }
        public long id_agenda_telefonica { get; set; }
        public Nullable<long> id_usuario { get; set; }
    
        public virtual tb_agenda_telefonica tb_agenda_telefonica { get; set; }
        public virtual tb_empresa tb_empresa { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
