//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFH.Web.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_estado_tarea_kanban
    {
        public tb_estado_tarea_kanban()
        {
            this.tb_tarea = new HashSet<tb_tarea>();
        }
    
        public long id_estado_tarea_kanban { get; set; }
        public string nombre_kanban { get; set; }
        public long id_empresa { get; set; }
        public Nullable<int> orden { get; set; }
    
        public virtual tb_empresa tb_empresa { get; set; }
        public virtual ICollection<tb_tarea> tb_tarea { get; set; }
    }
}
