//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFH.Web.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empresa
    {
        public tb_empresa()
        {
            this.tb_usuario = new HashSet<tb_usuario>();
            this.tb_detalle_agenda_telefonica = new HashSet<tb_detalle_agenda_telefonica>();
            this.tb_grupo = new HashSet<tb_grupo>();
            this.tb_fases_proyecto = new HashSet<tb_fases_proyecto>();
            this.tb_roles = new HashSet<tb_roles>();
            this.tb_estado_proyecto_kanban = new HashSet<tb_estado_proyecto_kanban>();
            this.tb_proyecto = new HashSet<tb_proyecto>();
        }
    
        public long id_empresa { get; set; }
        public string nombre_empresa { get; set; }
        public string url_empresa { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<long> usuario_creador { get; set; }
        public Nullable<bool> iniciada { get; set; }
        public Nullable<bool> inactivo { get; set; }
    
        public virtual ICollection<tb_usuario> tb_usuario { get; set; }
        public virtual ICollection<tb_detalle_agenda_telefonica> tb_detalle_agenda_telefonica { get; set; }
        public virtual ICollection<tb_grupo> tb_grupo { get; set; }
        public virtual ICollection<tb_fases_proyecto> tb_fases_proyecto { get; set; }
        public virtual ICollection<tb_roles> tb_roles { get; set; }
        public virtual ICollection<tb_estado_proyecto_kanban> tb_estado_proyecto_kanban { get; set; }
        public virtual ICollection<tb_proyecto> tb_proyecto { get; set; }
    }
}
