//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFH.Web.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_grupo_usuario
    {
        public long id_grupo_usuario { get; set; }
        public long id_usuario { get; set; }
        public long id_grupo { get; set; }
        public Nullable<long> id_empresa { get; set; }
    
        public virtual tb_grupo tb_grupo { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
