//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFH.Web.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_grupo
    {
        public tb_grupo()
        {
            this.tb_grupo_usuario = new HashSet<tb_grupo_usuario>();
        }
    
        public long id_grupo { get; set; }
        public string nombre_grupo { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public long id_empresa { get; set; }
        public Nullable<long> id_tipo_grupo { get; set; }
    
        public virtual tb_empresa tb_empresa { get; set; }
        public virtual ICollection<tb_grupo_usuario> tb_grupo_usuario { get; set; }
    }
}
