//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFH.Web.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_historia_usuario
    {
        public long id_historia { get; set; }
        public long id_empresa { get; set; }
        public long id_proyecto { get; set; }
        public string codigo { get; set; }
        public int id_prioridad { get; set; }
        public int id_riesgo { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> id_responsable { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<long> id_usuario_creador { get; set; }
        public Nullable<int> orden { get; set; }
    }
}
