//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFH.Web.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_plantilla_estados_proyectos_kanban
    {
        public int id_plantilla_proyectos_kanban { get; set; }
        public string nombre_kanban { get; set; }
        public Nullable<int> orden { get; set; }
    }
}
