//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFH.Web.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_proyecto
    {
        public tb_proyecto()
        {
            this.tb_evento = new HashSet<tb_evento>();
            this.tb_tarea = new HashSet<tb_tarea>();
        }
    
        public long id_proyecto { get; set; }
        public long id_empresa { get; set; }
        public string nombre_proyecto { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_inicio_estimado { get; set; }
        public Nullable<System.DateTime> fecha_fin_estimado { get; set; }
        public Nullable<System.DateTime> fecha_inicio_real { get; set; }
        public Nullable<System.DateTime> fecha_fin_real { get; set; }
        public Nullable<double> horas_estimadas { get; set; }
        public Nullable<long> id_responsable_proyecto { get; set; }
        public Nullable<long> id_responsable_proyecto_cliente { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public Nullable<long> id_usuario_creador { get; set; }
        public long id_cliente { get; set; }
        public long id_estado_proyecto_kanban { get; set; }
        public Nullable<bool> es_tutorial { get; set; }
        public string descripcion_proyecto { get; set; }
    
        public virtual tb_empresa tb_empresa { get; set; }
        public virtual tb_estado_proyecto_kanban tb_estado_proyecto_kanban { get; set; }
        public virtual ICollection<tb_evento> tb_evento { get; set; }
        public virtual ICollection<tb_tarea> tb_tarea { get; set; }
    }
}
