//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFH.Web.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_roles
    {
        public tb_roles()
        {
            this.tb_detalle_rol = new HashSet<tb_detalle_rol>();
        }
    
        public long id_rol { get; set; }
        public string nombre_rol { get; set; }
        public long id_empresa { get; set; }
        public Nullable<bool> inactivo { get; set; }
    
        public virtual ICollection<tb_detalle_rol> tb_detalle_rol { get; set; }
        public virtual tb_empresa tb_empresa { get; set; }
    }
}
