//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFH.Web.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        public tb_usuario()
        {
            this.tb_detalle_agenda_telefonica = new HashSet<tb_detalle_agenda_telefonica>();
            this.tb_detalle_rol = new HashSet<tb_detalle_rol>();
            this.tb_grupo_usuario = new HashSet<tb_grupo_usuario>();
        }
    
        public long id_usuario { get; set; }
        public string email_usuario { get; set; }
        public string clave { get; set; }
        public string nombre_usuario { get; set; }
        public string ap_paterno_usuario { get; set; }
        public string ap_materno_usuario { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public Nullable<bool> por_confirmar { get; set; }
        public long id_empresa { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual tb_empresa tb_empresa { get; set; }
        public virtual ICollection<tb_detalle_agenda_telefonica> tb_detalle_agenda_telefonica { get; set; }
        public virtual ICollection<tb_detalle_rol> tb_detalle_rol { get; set; }
        public virtual ICollection<tb_grupo_usuario> tb_grupo_usuario { get; set; }
    }
}
